# Generated by Django 4.2 on 2024-09-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='is_subscribed',
            field=models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=5),
        ),
    ]
