# Generated by Django 4.2 on 2024-09-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('Sofa and Bed', 'Sofa and Bed'), ('Modular Kitchen', 'Modular Kitchen'), ('Table and Chairs', 'Table and Chairs'), ('Cupboard', 'Cupboard')], default='Sofa and Bed', max_length=255),
        ),
    ]
